%%{init: { 'theme': 'default' } }%%
xychart-beta
    title "Importancia de modo sin conexión (%, n=122)"
    x-axis ["1", "2", "3", "4", "5"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [1.6, 4.1, 16.4, 16.4, 61.5]
