%%{init: { 'theme': 'neutral', 'themeVariables': { 'fontSize': '10px' } } }%%
xychart-beta
    title "Características más demandadas (Top 6) (%, n=121)"
    x-axis ["Actualización auto.", "Modo offline", "Recordatorios", "Compartir", "Recordar aprob.", "Asistente"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [88.4, 77.7, 56.2, 51.2, 45.5, 26.4]
