%%{init: { 'theme': 'default', 'pie': { 'textPosition': 0.5 }, 'themeVariables': { 'pieOuterStrokeWidth': 2, 'pieInnerRadius': 50 } } }%%
pie showData
    title Uso de mensajería para coordinar horarios (%, n=122)
    "Sí" : 80.3
    "No" : 19.7
