%%{init: { 'theme': 'default' } }%%
xychart-beta
    title "Sistema operativo principal del teléfono (%, n=123)"
    x-axis ["Android", "iOS", "Otro"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [94.3, 3.3, 2.4]
