%%{init: { 'theme': 'default' } }%%
xychart-beta
    title "Frecuencia de uso de Capuchino (%, n=124)"
    x-axis ["Solo en inscripción", "Varias veces/sem", "Raramente", "Nunca"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [44.4, 48.4, 4.8, 2.4]
