%%{init: { 'theme': 'neutral' } }%%
xychart-beta
    title "Nombre preferido (%, n=122)"
    x-axis ["Simón", "FCyT Planner", "MiHorario FCyT", "Otro"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [27.0, 27.0, 26.2, 19.7]

