xychart-beta
    title "Frecuencia de Uso de Capuchino"
    x-axis ["Solo durante la inscripción", "Varias veces por semestre", "Raramente", "Nunca lo he usado"]
    y-axis "Porcentaje (%)" 0 --> 50
    bar [48.4, 44.4, 7.3, 3.2]