%%{init: { 'theme': 'default' } }%%
xychart-beta
    title "Frustración por repetición (1–5) (%, n=123)"
    x-axis ["1", "2", "3", "4", "5"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [18.7, 21.1, 27.6, 20.3, 12.2]
