%%{init: { 'theme': 'default' } }%%
xychart-beta
    title "Utilidad percibida de notificaciones previas (%, n=123)"
    x-axis ["1", "2", "3", "4", "5"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [6.5, 10.6, 26.0, 14.6, 42.3]
