%%{init: { 'theme': 'neutral' } }%%
xychart-beta
    title "¿Tener app similar? (%, n=121)"
    x-axis ["Sí", "Depende", "No"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [71.1, 23.1, 5.8]

