%%{init: { 'theme': 'neutral' } }%%
xychart-beta
    title "¿La usaría regularmente? (%, n=122)"
    x-axis ["Sí", "Tal vez", "No"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [66.4, 27.0, 6.6]

