xychart-beta
    title "Demandas Clave de los Estudiantes"
    x-axis ["Modo sin conexión", "Recordatorios de clases", "Compartir mi horario", "Horarios actualizados automáticamente"]
    y-axis "Porcentaje (%)" 0 --> 90
    bar [77.7, 56.2, 51.2, 88.4]