%%{init: {
  'theme': 'default',
  'themeVariables': {
    'xyChart': {
      'plotColorPalette': '#4CAF50, #F44336, #2196F3, #FF9800'
    }
  }
}}%%
xychart-beta
    title "Dispositivo utilizado para ver horarios (%, n=126)"
    x-axis ["Laptop", "Teléfono Android", "iPhone", "Tablet"]
    y-axis "Porcentaje (%)" 0 --> 100
    %% Laptop -> verde
    bar [25.8, -1.9, -1.9, -1.9]
    %% Teléfono Android -> rojo
    bar [-1.9, 71.7, -1.9, -1.9]
    %% iPhone -> azul
    bar [-1.9, -1.9, 2.5, -1.9]
    %% Tablet -> naranja (0%, oculto)
    bar [-1.9, -1.9, -1.9, -1.9]
