%%{init: { 'theme': 'default' } }%%
xychart-beta
    title "Dispositivo habitual para Capuchino (%, n=120)"
    x-axis ["Laptop", "Teléfono Android", "iPhone", "Tablet"]
    y-axis "Porcentaje" 0 --> 100
    bar "Porcentaje" [25.8, 71.7, 2.5, 0.0]
