%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontFamily": "Helvetica, Arial, sans-serif",
    "fontSize": "24px"
  },
  "er": {
    "layoutDirection": "LR",
    "entityPadding": 24,
    "useMaxWidth": true
  }
}}%%

erDiagram
    CAREERS {
        text code PK
        text name UK
        text pdf_url UK
        text updated_date
        text last_sync_time
        integer is_enabled
    }

    LEVELS {
        integer id PK
        text name UK
    }

    CAREER_LEVELS {
        text career_code PK
        integer level_id PK
    }

    CAREERS ||--o{ CAREER_LEVELS : relaciona
    LEVELS ||--o{ CAREER_LEVELS : relaciona
