%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontFamily": "Helvetica, Arial, sans-serif",
    "fontSize": "24px"
  },
  "er": {
    "layoutDirection": "LR",
    "entityPadding": 24,
    "useMaxWidth": true
  }
}}%%

erDiagram
    CAREERS {
        text code PK
        text name
    }

    SUBJECTS {
        text code PK
        text name
        integer is_active
    }

    LEVELS {
        integer id PK
        text name
    }

    GROUPS {
        integer id PK
        text subject_code FK
        text group_id
        integer level_id FK
        text group_name
        text type
        integer is_active
        text modality
    }

    CAREER_SUBJECT_GROUPS {
        text career_code PK
        integer group_id PK
    }

    SUBJECTS ||--o{ GROUPS : agrupa
    LEVELS ||--o{ GROUPS : clasifica
    CAREERS ||--o{ CAREER_SUBJECT_GROUPS : oferta
    GROUPS ||--o{ CAREER_SUBJECT_GROUPS : pertenece
